name: check verify
on:
  pull_request:
  workflow_dispatch:

jobs:
  check_verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v4
        with:
          go-version: '>=1.21.5'

      - name: Run Tests
        run:  go test ./... -v

      - name: Build app
        run: go build -o build/scrapper cmd/main.go


